### ISSUE TITLE
recorder button missing?

### ISSUE THREAD

**Issue by rdrll** [Ordinath/Whisper_to_ChatGPT#5]
Have been using it for a long while, but recent few days the recorder button doesn't seem to appear?

Screenshot attached below

-------------

![image](https://user-images.githubusercontent.com/13176405/232023746-515e9bc2-4d1a-4f6d-9f22-0b92e18867ca.png)

**Comment by Ordinath** [comment]
Hey there! 
This happened due to openai change of chatGPT website routing. 
This is fixed and awaits approval from the Google web store for a new version release.

If you dont wanna wait, just replace 

``` "matches": ["https://chat.openai.com/chat*"], ```

to 

```"matches": ["https://chat.openai.com/*"],```

in the manifest.json or clone the current main branch and load the chrome extension unpacked
