### ISSUE TITLE
Since a few days the plugin does not work anymore

### ISSUE THREAD

**Issue by khamaileon** [Ordinath/Whisper_to_ChatGPT#7]
![image](https://user-images.githubusercontent.com/1322166/232416266-7b6a7306-0f72-4583-8cd3-8f470f5c3867.png)

I'm using the version 1.2.6 on Chromium Version 111.0.5563.146 (Official Build) snap (64-bit) on Ubuntu 20.04.06 LTS

**Comment by Ordinath** [comment]
it's incredible how long google takes to approve literally one character change in the manifest, but it is what it is...
Up until the point when 1.2.7 would be approved the only workaround I have is

- go on an existing chat page, **not** the new chat
- refresh the page completely
- since existing chats have URLs like "https://chat.openai.com/c/{id}" the button should appear
- after this, you can create new chats and the button should remain

**Comment by khamaileon** [comment]
Thanks for the answer. Unfortunately I had deleted all the conversations!

But that's ok, I'll wait for the update :)

**Comment by Ordinath** [comment]
Ok, google finally reviewed my 1 character change and 1.2.7 is live 😄

**Comment by khamaileon** [comment]
Great! It's working thank you! BTW I had to uninstall and reinstall the addon because Google didn't suggest me an update.
